### ISSUE TITLE
AD/LDS Change detection - Ignoring explicit credentials

### ISSUE THREAD

**Issue by Josera83** [lithnet/miis-autosync#153]
Hello,

I'm facing an issue with Active Directory Agents from Lithnet, I have installed MIM Sync and Autosync in domain ABC.COM, and I have two agents for Active Directory, domains are: Source1.com and Source2.com.

I have set AD/LDS Change detection and specifying credentials in this format: Source1\Username, but whenever try to start the agent for AD I receive this error:

Could not start the listener
System.DirectoryServices.Protocols.LdapException: The supplied credential is invalid.
   at System.DirectoryServices.Protocols.LdapConnection.BindHelper(NetworkCredential newCredential, Boolean needSetCredential)
   at System.DirectoryServices.Protocols.LdapConnection.SendRequestHelper(DirectoryRequest request, Int32& messageID)
   at System.DirectoryServices.Protocols.LdapConnection.BeginSendRequest(DirectoryRequest request, TimeSpan requestTimeout, PartialResultProcessing partialMode, AsyncCallback callback, Object state)
   at Lithnet.Miiserver.AutoSync.ActiveDirectoryChangeTrigger.SetupListener()

I have checked the Security logs in Domain controllers in Source1 and Source2, I found application is using the autosync service account credentials instead of the specific credentials for every domain. I already restarted the MIM Sync and Lithnet Autosync services but no luck.

Thanks in advance.

**Comment by ryannewington** [comment]
@Josera83 are you able to email me your autosync config file - ryan@lithnet.io

**Comment by ryannewington** [comment]
@Josera83 thanks for sending it through. Can you try the latest version of autosync? I just fixed a bug where usernames in the format of domain\user were not being processed correctly.

**Comment by Josera83** [comment]
Hi Ryan,

I just tried with latest release and it didn't work using the format DOMAIN\User, but with UPN format.

When I tried using the failed format an Event ID 4625 is generated and I realized that security entry doesn't include the "Account Domain" value... really weird.

Log Name:      Security
Source:        Microsoft-Windows-Security-Auditing
Date:          5/1/2018 2:09:18 PM
Event ID:      4625
Task Category: Logon
Level:         Information
Keywords:      Audit Failure
User:          N/A
Computer:      DC1.Domain1.com
Description:
An account failed to log on.

Subject:
	Security ID:		NULL SID
	Account Name:		-
	Account Domain:		-
	Logon ID:		0x0

Logon Type:			3

Account For Which Logon Failed:
	Security ID:		NULL SID
	Account Name:		Domain1\AD_Sync
	Account Domain:		

Failure Information:
	Failure Reason:		Unknown user name or bad password.
	Status:			0xc000006d
	Sub Status:		0xc0000064

After the error I tried using the UPN format and it worked, in security log an event 4624 is generated showing the Account Domain, now trigger is listening and detecting all AD changes.

New Logon:
	Security ID:		Domain1\AD_Sync
	Account Name:		AD_Sync
	Account Domain:		Domain1
	Logon ID:		0x3BDC9648
	Logon GUID:		{00000000-0000-0000-0000-000000000000}

Thank you very much.

**Comment by ryannewington** [comment]
@Josera83 The latest version definitely should have fixed that. Could I trouble you to send me the autosync service log file, after attempting to start the MA controller with a trigger trying to logon as domain\user?

**Comment by Josera83** [comment]
Hi Ryan,

I thought that I already updated the version, I just checked but I still have the previous one:

![version](https://user-images.githubusercontent.com/38770615/40142929-933cbc78-5949-11e8-9298-deaab465f73b.PNG)

Do I need to remove the current version before install the new one?

Thank you.

**Comment by ryannewington** [comment]
No you can install over the top and it will upgrade

**Comment by Josera83** [comment]
Hi Ryan,

I tried three times to download the MSI file from this link:
https://github.com/lithnet/miis-autosync/releases/download/v1.2.6692/autosync.msi

After the update the version is 1.1.6682.50548:

![file version](https://user-images.githubusercontent.com/38770615/40184058-d164174a-59de-11e8-9bad-630ccf40dd17.PNG)

I already tried doing a fresh installation but I get the same results.

Best regards.

**Comment by ryannewington** [comment]
@Josera83 I'm really sorry about that mate. I don't know what happened there. I have reuploaded the correct build to this release https://github.com/lithnet/miis-autosync/releases/tag/v1.2.6713

**Comment by Josera83** [comment]
Hi Ryan,

Sorry for delay, I was able to set the Sync account using the DOMAIN\User format using the version 1.2.6713.

Thank you very much.
